version: "3.7"

services:
  scruffy:
    build:
      context: .
      target: scruffy-the-monster-build
      dockerfile: Dockerfile
    image: scruffy/scruffy:1.0
    ports:
      - "9000-9005:9000"
