version: "3.7"

services:
  scruffy:
    build:
      context: .
      target: scruffy-the-monster-build
      dockerfile: Dockerfile
    image: scruffy/scruffy:1.0
    container_name: scruffy_RC
    ports:
      - "9000:9000"
